version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    ignored_updates:
      - match:
          dependency_name: "d3"
      - match:
          dependency_name: "leaflet"
      - match:
          dependency_name: "leaflet-draw"
      - match:
          dependency_name: "leaflet.nontiledlayer"
      - match:
          dependency_name: "react-leaflet"
      - match:
          dependency_name: "redux-saga"
      - match:
          dependency_name: "jest-styled-components"
      - match:
          dependency_name: "escape-string-regexp"
      - match:
          dependency_name: "marked"
